//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for the Certificate Management page.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceBackgroundCheckSystem
{
    public partial class CertificateManagement
    {
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblTotalCertificates;
        protected global::System.Web.UI.WebControls.Label lblIssuedToday;
        protected global::System.Web.UI.WebControls.Label lblPaidApplications;
        protected global::System.Web.UI.WebControls.Label lblAwaitingCertificates;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.GridView gvCertificates;
    }
}
