//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for the Payment Monitoring page.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace PoliceBackgroundCheckSystem
{
    public partial class PaymentMonitoring
    {
        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.Label lblTotalAmount;

        protected global::System.Web.UI.WebControls.Label lblTotalPayments;

        protected global::System.Web.UI.WebControls.Label lblVerifiedPayments;

        protected global::System.Web.UI.WebControls.Label lblUnverifiedPayments;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.DropDownList ddlMethod;

        protected global::System.Web.UI.WebControls.DropDownList ddlVerification;

        protected global::System.Web.UI.WebControls.Button btnFilter;

        protected global::System.Web.UI.WebControls.GridView gvPayments;
    }
}